"""Dagster resources."""
import os
from pathlib import Path

from dagster_dbt import DbtCliResource

# dbt manifest path (generated by `dbt parse` at build time)
DBT_MANIFEST = Path(__file__).parent / "target" / "manifest.json"

# dbt resource — target from DBT_TARGET env var (default: dev for local)
dbt_resource = DbtCliResource(
    project_dir=Path(__file__).parent,
    profiles_dir=Path(__file__).parent,
    target=os.getenv("DBT_TARGET", "dev"),
)
