apiVersion: v1
kind: Service
metadata:
  name: liveball-data-feed
  namespace: stateball
spec:
  selector:
    app: liveball-data-feed
  ports:
    - name: http
      port: 8001
      targetPort: 8001
