apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - data-feed-deployment.yaml
  - data-feed-service.yaml
  - sim-worker-deployment.yaml
  - redis-statefulset.yaml
  - redis-service.yaml
  - externalsecret.yaml
